version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMADB_ENV=dev

  python-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_service
    ports:
      - "5000:5000"
    env_file:
      - .env
